
-- =====================================================
-- IMAGE MODELS (30)
-- credits = ceil(usd_cost * 16) with 60% margin and 1 MC = $0.10
-- =====================================================

INSERT INTO public.fal_image_models (slug, display_name, provider, description, endpoint_text_to_image, endpoint_image_to_image, endpoint_multi_reference, unit, fal_unit_cost_usd, credits, supports_multi_image, max_input_images, supported_aspects, supported_resolutions, default_aspect, default_resolution, is_premium, is_new, is_featured, sort_order) VALUES
-- Featured / Newest
('nano-banana-pro', 'Nano Banana Pro', 'Google', 'Google''s state-of-the-art image generation and editing model with native typography and multi-image fusion.', 'fal-ai/nano-banana-pro', 'fal-ai/nano-banana-pro/edit', 'fal-ai/nano-banana-pro/edit', 'image', 0.10, 2, true, 6, '["1:1","3:2","2:3","4:3","3:4","16:9","9:16","21:9"]', '["1K","2K","4K"]', '1:1', '2K', true, true, true, 1),
('nano-banana-2', 'Nano Banana 2', 'Google', 'Google''s fast state-of-the-art image generation and editing model.', 'fal-ai/nano-banana-2', 'fal-ai/nano-banana-2/edit', 'fal-ai/nano-banana-2/edit', 'image', 0.04, 1, true, 6, '["1:1","3:2","2:3","4:3","3:4","16:9","9:16"]', '["1K","2K"]', '1:1', '1K', false, true, true, 2),
('gpt-image-2', 'GPT Image 2', 'OpenAI', 'OpenAI''s latest image model with exceptional typography and fine-grained edits.', 'openai/gpt-image-2', 'openai/gpt-image-2/edit', 'openai/gpt-image-2/edit', 'image', 0.10, 2, true, 4, '["1:1","3:2","2:3"]', '["1024","1536","2048"]', '1:1', '1024', true, true, true, 3),
('gpt-image-1-5', 'GPT Image 1.5', 'OpenAI', 'High-fidelity images with strong prompt adherence and composition.', 'fal-ai/gpt-image-1.5', NULL, NULL, 'image', 0.05, 1, false, 1, '["1:1","3:2","2:3"]', '["1024","1536"]', '1:1', '1024', false, true, false, 4),
('flux-2-pro', 'FLUX.2 [pro]', 'Black Forest Labs', 'Top-tier text-to-image and editing from BFL with crisp text and photorealism.', 'fal-ai/flux-2-pro', 'fal-ai/flux-2-pro/edit', 'fal-ai/flux-2-pro/edit', 'image', 0.06, 1, true, 4, '["1:1","3:2","2:3","16:9","9:16","21:9"]', '["1K","2K"]', '1:1', '1K', true, true, true, 5),
('flux-2-dev', 'FLUX.2 [dev]', 'Black Forest Labs', 'Open dev tier of FLUX.2 with enhanced realism and native editing.', 'fal-ai/flux-2', NULL, NULL, 'image', 0.03, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, true, false, 6),
('flux-2-klein-9b', 'FLUX.2 [klein] 9B', 'Black Forest Labs', 'Lightweight 9B FLUX.2 variant for fast generation.', 'fal-ai/flux-2/klein/9b', NULL, NULL, 'image', 0.02, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, true, false, 7),
('flux-pro-1-1-ultra', 'FLUX 1.1 [pro] Ultra', 'Black Forest Labs', 'Up to 2K resolution with improved photo-realism.', 'fal-ai/flux-pro/v1.1-ultra', NULL, NULL, 'image', 0.06, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16","21:9"]', '["2K"]', '1:1', '2K', true, false, false, 8),
('flux-pro-1-1', 'FLUX 1.1 [pro]', 'Black Forest Labs', 'Improved composition and detail over FLUX.1 pro.', 'fal-ai/flux-pro/v1.1', NULL, NULL, 'image', 0.04, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K","2K"]', '1:1', '1K', false, false, false, 9),
('flux-pro-kontext', 'FLUX Kontext [pro]', 'Black Forest Labs', 'Reference-image editing for targeted local edits and scene transformations.', NULL, 'fal-ai/flux-pro/kontext', 'fal-ai/flux-pro/kontext', 'image', 0.04, 1, true, 4, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, false, true, 10),
('flux-dev', 'FLUX.1 [dev]', 'Black Forest Labs', '12B flow transformer for high-quality images.', 'fal-ai/flux/dev', NULL, NULL, 'image', 0.025, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, false, false, 11),
('flux-schnell', 'FLUX.1 [schnell]', 'Black Forest Labs', 'Ultra-fast 1-4 step generation.', 'fal-ai/flux/schnell', NULL, NULL, 'image', 0.003, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, false, false, 12),
('flux-lora', 'FLUX LoRA', 'Black Forest Labs', 'FLUX.1 dev with LoRA support for personalization and brand identities.', 'fal-ai/flux-lora', NULL, NULL, 'image', 0.05, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, false, false, 13),
('seedream-v5-lite', 'Seedream 5.0 Lite', 'ByteDance', 'New-gen unified image creation and editing, fast tier.', 'fal-ai/bytedance/seedream/v5/lite/text-to-image', 'fal-ai/bytedance/seedream/v5/lite/edit', 'fal-ai/bytedance/seedream/v5/lite/edit', 'image', 0.025, 1, true, 4, '["1:1","3:2","2:3","16:9","9:16"]', '["1K","2K"]', '1:1', '1K', false, true, true, 14),
('seedream-v4-5', 'Seedream 4.5', 'ByteDance', 'Unified generation and editing model.', 'fal-ai/bytedance/seedream/v4.5/text-to-image', 'fal-ai/bytedance/seedream/v4.5/edit', 'fal-ai/bytedance/seedream/v4.5/edit', 'image', 0.04, 1, true, 4, '["1:1","3:2","2:3","16:9","9:16","21:9"]', '["1K","2K"]', '1:1', '1K', false, true, false, 15),
('seedream-v4', 'Seedream 4.0', 'ByteDance', 'Seedream 4.0 unified generation and editing.', 'fal-ai/bytedance/seedream/v4/text-to-image', 'fal-ai/bytedance/seedream/v4/edit', 'fal-ai/bytedance/seedream/v4/edit', 'image', 0.03, 1, true, 4, '["1:1","3:2","2:3","16:9","9:16"]', '["1K","2K"]', '1:1', '1K', false, false, false, 16),
('ideogram-v3', 'Ideogram V3', 'Ideogram', 'Exceptional typography and posters/logos generation.', 'fal-ai/ideogram/v3', NULL, NULL, 'image', 0.06, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K","2K"]', '1:1', '1K', false, false, false, 17),
('recraft-v4-1-pro', 'Recraft V4.1 Pro', 'Recraft', 'Hi-res 2048 raster output for hero imagery and print.', 'fal-ai/recraft/v4.1/pro/text-to-image', NULL, NULL, 'image', 0.06, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16","21:9"]', '["1K","2K"]', '1:1', '2K', true, true, false, 18),
('recraft-v4-1', 'Recraft V4.1', 'Recraft', 'Design-first raster generation.', 'fal-ai/recraft/v4.1/text-to-image', NULL, NULL, 'image', 0.04, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, true, false, 19),
('recraft-v4-1-vector', 'Recraft V4.1 Vector', 'Recraft', 'Fully editable SVGs with structured layers.', 'fal-ai/recraft/v4.1/text-to-vector', NULL, NULL, 'image', 0.04, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, true, false, 20),
('grok-imagine-image', 'Grok Imagine', 'xAI', 'Highly aesthetic generation and editing from xAI.', 'xai/grok-imagine-image', 'xai/grok-imagine-image/edit', 'xai/grok-imagine-image/edit', 'image', 0.06, 1, true, 4, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, true, false, 21),
('z-image-turbo', 'Z-Image Turbo', 'Tongyi-MAI', 'Super-fast 6B text-to-image model.', 'fal-ai/z-image/turbo', NULL, NULL, 'image', 0.01, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, true, false, 22),
('qwen-image', 'Qwen Image', 'Alibaba', 'Strong general-purpose model from Alibaba.', 'fal-ai/qwen-image', NULL, NULL, 'megapixel', 0.02, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, false, false, 23),
('imagineart-2-0-edit', 'ImagineArt 2.0 Edit', 'ImagineArt', 'Precise prompt-guided editing at 2K resolution.', NULL, 'imagineart/imagineart-2.0-edit-preview/image-to-image', 'imagineart/imagineart-2.0-edit-preview/image-to-image', 'image', 0.04, 1, true, 4, '["1:1","3:2","2:3","16:9","9:16"]', '["1K","2K"]', '1:1', '2K', false, true, false, 24),
('reve-edit', 'Reve Edit', 'Reve', 'Upload an image and transform it via a text prompt.', NULL, 'fal-ai/reve/edit', NULL, 'image', 0.04, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, false, false, 25),
('bria-fibo-edit', 'Bria Fibo-Edit', 'Bria', 'High-fidelity enterprise-safe editing with JSON+Mask+Image.', NULL, 'bria/fibo-edit/edit', NULL, 'image', 0.06, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', true, false, false, 26),
('nano-banana', 'Nano Banana', 'Google', 'Google''s original Nano Banana generation and editing model.', 'fal-ai/nano-banana', 'fal-ai/nano-banana/edit', 'fal-ai/nano-banana/edit', 'image', 0.04, 1, true, 4, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, false, false, 27),
('fast-sdxl', 'Fast SDXL', 'Stability', 'SDXL at the speed of light.', 'fal-ai/fast-sdxl', NULL, NULL, 'image', 0.005, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, false, false, 28),
('flux-pro-erase', 'FLUX Pro Erase', 'Black Forest Labs', 'Remove undesired objects and text from images.', NULL, 'fal-ai/flux-pro/v1/erase', NULL, 'image', 0.04, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["1K"]', '1:1', '1K', false, true, false, 29),
('seedvr-upscale', 'SeedVR Upscale', 'ByteDance', 'High-quality image upscaling.', NULL, 'fal-ai/seedvr/upscale/image', NULL, 'image', 0.05, 1, false, 1, '["1:1","3:2","2:3","16:9","9:16"]', '["2K","4K"]', '1:1', '4K', false, false, false, 30);


-- =====================================================
-- VIDEO MODELS (30) — per-second pricing unless noted
-- credits_per_second = ceil(cost_per_second_usd * 16)
-- =====================================================

INSERT INTO public.fal_video_models (slug, display_name, provider, description, endpoint_text_to_video, endpoint_image_to_video, endpoint_reference_to_video, endpoint_start_end_frame, unit, cost_per_second_usd, cost_per_video_usd, credits_per_second, credits_per_video, supports_multi_image, max_input_images, supports_start_end_frame, supports_audio, supported_aspects, supported_resolutions, supported_durations, default_aspect, default_resolution, default_duration, is_premium, is_new, is_featured, sort_order) VALUES
-- Featured / Newest
('seedance-2-0', 'Seedance 2.0', 'ByteDance', 'Most advanced video model with cinematic output, native audio, real-world physics, and director-level camera control.', 'bytedance/seedance-2.0/text-to-video', 'bytedance/seedance-2.0/image-to-video', 'bytedance/seedance-2.0/reference-to-video', 'bytedance/seedance-2.0/image-to-video', 'second', 0.10, NULL, 2, NULL, true, 9, true, true, '["16:9","9:16","1:1","4:3","3:4","21:9"]', '["720p","1080p"]', '[5,8,10]', '16:9', '1080p', 5, true, true, true, 1),
('seedance-2-0-fast', 'Seedance 2.0 Fast', 'ByteDance', 'Lower-latency and lower-cost tier of Seedance 2.0 with native audio and start/end frame control.', 'bytedance/seedance-2.0/fast/text-to-video', 'bytedance/seedance-2.0/fast/image-to-video', 'bytedance/seedance-2.0/fast/reference-to-video', 'bytedance/seedance-2.0/fast/image-to-video', 'second', 0.05, NULL, 1, NULL, true, 9, true, true, '["16:9","9:16","1:1"]', '["720p","1080p"]', '[5,8,10]', '16:9', '720p', 5, false, true, true, 2),
('kling-v3-pro', 'Kling 3.0 Pro', 'Kling', 'Top-tier image-to-video with cinematic visuals, fluid motion, and native audio.', 'fal-ai/kling-video/v3/pro/text-to-video', 'fal-ai/kling-video/v3/pro/image-to-video', NULL, NULL, 'second', 0.10, NULL, 2, NULL, false, 1, false, true, '["16:9","9:16","1:1"]', '["1080p"]', '[5,10]', '16:9', '1080p', 5, true, true, true, 3),
('kling-2-5-turbo-pro', 'Kling 2.5 Turbo Pro', 'Kling', 'Fast and high-quality image-to-video.', NULL, 'fal-ai/kling-video/v2.5-turbo/pro/image-to-video', NULL, NULL, 'second', 0.07, NULL, 2, NULL, false, 1, false, false, '["16:9","9:16","1:1"]', '["1080p"]', '[5,10]', '16:9', '1080p', 5, false, false, false, 4),
('veo-3-1-fast', 'Veo 3.1 Fast', 'Google', 'Latest Veo 3.1 fast tier with reference-to-video, text-to-video and image-to-video.', 'fal-ai/veo3.1/fast/text-to-video', 'fal-ai/veo3.1/fast/image-to-video', 'fal-ai/veo3.1/fast/reference-to-video', NULL, 'second', 0.10, NULL, 2, NULL, true, 3, false, true, '["16:9","9:16"]', '["720p","1080p"]', '[5,8]', '16:9', '720p', 5, true, true, true, 5),
('veo-3', 'Veo 3', 'Google', 'Premium cinematic video model with native audio.', 'fal-ai/veo3/text-to-video', 'fal-ai/veo3/image-to-video', NULL, NULL, 'second', 0.40, NULL, 7, NULL, false, 1, false, true, '["16:9","9:16"]', '["720p","1080p"]', '[3,5,8]', '16:9', '720p', 5, true, false, false, 6),
('pixverse-v6', 'PixVerse V6', 'PixVerse', 'Lifelike physics and striking visuals.', 'fal-ai/pixverse/v6/text-to-video', 'fal-ai/pixverse/v6/image-to-video', NULL, 'fal-ai/pixverse/v6/image-to-video', 'second', 0.05, NULL, 1, NULL, false, 1, true, false, '["16:9","9:16","1:1"]', '["720p","1080p"]', '[5,8]', '16:9', '720p', 5, false, true, false, 7),
('wan-2-5', 'Wan 2.5', 'Alibaba', 'Cost-efficient text-to-video and image-to-video.', 'fal-ai/wan-25-preview/text-to-video', 'fal-ai/wan-25-preview/image-to-video', NULL, NULL, 'second', 0.05, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16","1:1"]', '["720p","1080p"]', '[5,10]', '16:9', '720p', 5, false, true, false, 8),
('wan-2-2', 'Wan 2.2', 'Alibaba', 'Image-to-video from Alibaba Wan family.', NULL, 'fal-ai/wan-v2.2-a14b/image-to-video', NULL, NULL, 'second', 0.04, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16","1:1"]', '["720p"]', '[5]', '16:9', '720p', 5, false, false, false, 9),
('hailuo-02-pro', 'Hailuo 02 Pro', 'MiniMax', 'Pro tier of MiniMax Hailuo with start/end frame control.', 'fal-ai/minimax/hailuo-02-pro/text-to-video', 'fal-ai/minimax/hailuo-02-pro/image-to-video', NULL, 'fal-ai/minimax/hailuo-02-pro/image-to-video', 'second', 0.08, NULL, 2, NULL, false, 1, true, false, '["16:9","9:16","1:1"]', '["1080p"]', '[6,10]', '16:9', '1080p', 6, false, false, false, 10),
('hailuo-02', 'Hailuo 02', 'MiniMax', 'Fast and affordable text-to-video and image-to-video.', 'fal-ai/minimax/hailuo-02/text-to-video', 'fal-ai/minimax/hailuo-02/image-to-video', NULL, NULL, 'second', 0.045, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16","1:1"]', '["720p"]', '[6,10]', '16:9', '720p', 6, false, false, false, 11),
('runway-gen-4', 'Runway Gen-4', 'Runway', 'Cinematic image-to-video with multi-reference.', NULL, 'fal-ai/runway-gen4/image-to-video', 'fal-ai/runway-gen4/reference-to-video', NULL, 'second', 0.20, NULL, 4, NULL, true, 4, false, false, '["16:9","9:16","1:1"]', '["720p","1080p"]', '[5,10]', '16:9', '720p', 5, true, false, false, 12),
('runway-gen-4-turbo', 'Runway Gen-4 Turbo', 'Runway', 'Fast turbo tier of Gen-4.', NULL, 'fal-ai/runway-gen4-turbo/image-to-video', NULL, NULL, 'second', 0.05, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16","1:1"]', '["720p"]', '[5,10]', '16:9', '720p', 5, false, false, false, 13),
('luma-ray-2', 'Luma Ray 2', 'Luma', 'Smooth cinematic video with start/end frame support.', 'fal-ai/luma-dream-machine/ray-2', 'fal-ai/luma-dream-machine/ray-2/image-to-video', NULL, 'fal-ai/luma-dream-machine/ray-2/image-to-video', 'second', 0.18, NULL, 3, NULL, false, 1, true, false, '["16:9","9:16","1:1","4:3","21:9"]', '["720p","1080p"]', '[5,9]', '16:9', '720p', 5, true, false, false, 14),
('luma-ray-2-flash', 'Luma Ray 2 Flash', 'Luma', 'Faster cheaper tier of Ray 2.', 'fal-ai/luma-dream-machine/ray-2-flash', 'fal-ai/luma-dream-machine/ray-2-flash/image-to-video', NULL, NULL, 'second', 0.05, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16","1:1"]', '["720p"]', '[5,9]', '16:9', '720p', 5, false, false, false, 15),
('pika-2-2', 'Pika 2.2', 'Pika', 'High-quality T2V/I2V with start/end frame.', 'fal-ai/pika/v2.2/text-to-video', 'fal-ai/pika/v2.2/image-to-video', NULL, 'fal-ai/pika/v2.2/image-to-video', 'second', 0.08, NULL, 2, NULL, false, 1, true, false, '["16:9","9:16","1:1"]', '["720p","1080p"]', '[5,10]', '16:9', '720p', 5, false, false, false, 16),
('ltx-video-13b', 'LTX-Video 13B', 'Lightricks', 'Fast 13B video generation.', 'fal-ai/ltx-video-13b-distilled/multiconditioning', 'fal-ai/ltx-video-13b-distilled/image-to-video', NULL, NULL, 'second', 0.04, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16","1:1"]', '["720p"]', '[5,10]', '16:9', '720p', 5, false, false, false, 17),
('framepack', 'Framepack', 'Lightricks', 'Frame-by-frame video generation with start/end control.', NULL, 'fal-ai/framepack', NULL, 'fal-ai/framepack/i2v-flf', 'second', 0.04, NULL, 1, NULL, false, 1, true, false, '["16:9","9:16","1:1"]', '["720p"]', '[5,10]', '16:9', '720p', 5, false, false, false, 18),
('cogvideo-x', 'CogVideoX', 'Tsinghua', 'Open video generation.', 'fal-ai/cogvideox-5b', 'fal-ai/cogvideox-5b/image-to-video', NULL, NULL, 'second', 0.04, NULL, 1, NULL, false, 1, false, false, '["16:9"]', '["720p"]', '[6]', '16:9', '720p', 6, false, false, false, 19),
('mochi-1', 'Mochi 1', 'Genmo', 'High-quality open video model.', 'fal-ai/mochi-v1', NULL, NULL, NULL, 'second', 0.05, NULL, 1, NULL, false, 1, false, false, '["16:9"]', '["480p","720p"]', '[5]', '16:9', '720p', 5, false, false, false, 20),
('hunyuan-video', 'Hunyuan Video', 'Tencent', 'Tencent open video model.', 'fal-ai/hunyuan-video', 'fal-ai/hunyuan-video-image-to-video', NULL, NULL, 'second', 0.05, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16"]', '["720p"]', '[5,10]', '16:9', '720p', 5, false, false, false, 21),
('open-sora-2', 'Open-Sora 2', 'HPC-AI', 'Open community video generation.', 'fal-ai/open-sora-v2/text-to-video', NULL, NULL, NULL, 'second', 0.04, NULL, 1, NULL, false, 1, false, false, '["16:9"]', '["720p"]', '[5]', '16:9', '720p', 5, false, false, false, 22),
('step-video-2', 'Step-Video 2', 'StepFun', 'High-quality T2V from StepFun.', 'fal-ai/stepvideo', NULL, NULL, NULL, 'second', 0.05, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16"]', '["720p"]', '[5]', '16:9', '720p', 5, false, false, false, 23),
('vidu-q1', 'Vidu Q1', 'Vidu', 'I2V with multi-reference and start/end frame.', NULL, 'fal-ai/vidu/q1/image-to-video', 'fal-ai/vidu/q1/reference-to-video', 'fal-ai/vidu/q1/start-end-to-video', 'second', 0.06, NULL, 1, NULL, true, 7, true, false, '["16:9","9:16","1:1"]', '["720p"]', '[4,8]', '16:9', '720p', 4, false, false, false, 24),
('haiper-2-5', 'Haiper 2.5', 'Haiper', 'Smooth T2V and I2V.', 'fal-ai/haiper-video-v2.5/text-to-video', 'fal-ai/haiper-video-v2.5/image-to-video', NULL, NULL, 'second', 0.05, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16"]', '["720p"]', '[4,8]', '16:9', '720p', 4, false, false, false, 25),
('magi-1', 'Magi 1', 'Sand AI', 'Cinematic autoregressive video.', NULL, 'fal-ai/magi-distilled/image-to-video', NULL, NULL, 'second', 0.05, NULL, 1, NULL, false, 1, false, false, '["16:9"]', '["720p"]', '[5]', '16:9', '720p', 5, false, false, false, 26),
('dreamina-3-1', 'Dreamina 3.1', 'ByteDance', 'High-quality ByteDance Dreamina I2V.', NULL, 'fal-ai/dreamina/v3.1/image-to-video', NULL, NULL, 'second', 0.06, NULL, 1, NULL, false, 1, false, false, '["16:9","9:16","1:1"]', '["720p","1080p"]', '[5,10]', '16:9', '720p', 5, false, true, false, 27),
('happy-horse-video-edit', 'HappyHorse Video Edit', 'Alibaba', 'Natural-language video editing with up to 5 reference images.', NULL, NULL, 'alibaba/happy-horse/video-edit', NULL, 'second', 0.06, NULL, 1, NULL, true, 5, false, false, '["16:9","9:16"]', '["720p"]', '[5]', '16:9', '720p', 5, false, true, false, 28),
('ovi', 'Ovi', 'Character AI', 'I2V with audio (per-video billing).', NULL, 'fal-ai/ovi/image-to-video', NULL, NULL, 'video', NULL, 0.20, NULL, 4, false, 1, false, true, '["16:9","9:16"]', '["720p"]', '[5]', '16:9', '720p', 5, false, false, false, 29),
('heygen-avatar-5', 'HeyGen Avatar V', 'HeyGen', 'Talking digital-twin avatar from text or audio with lip-sync.', 'fal-ai/heygen/avatar5/digital-twin', NULL, NULL, NULL, 'second', 0.10, NULL, 2, NULL, false, 1, false, true, '["16:9","9:16","1:1"]', '["720p","1080p"]', '[10,20,30,60]', '9:16', '720p', 10, true, true, false, 30);
